#!/bin/sh
. /etc/rc.common

StartService ()
{
    ConsoleMessage "Running SpoofMACAddress script."
    python (path to python)
}

StopService ()
{
    return 0
}

RestartService ()
{
    return 0
}

RunService "$1"
